import{a as f,S as w,i as n}from"./assets/vendor-D3PmPE7A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const L="48876582-9b859673e779d9e5d61f29cd8",S="https://pixabay.com/api/";async function y(o,t=1,i=40){const l=new URLSearchParams({key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}),e=S+`?${l}`;try{return await f.get(e)}catch(r){return console.error("Error fetching images:",r),null}}function h(o){const t=document.querySelector(".gallery"),i=o.map(s=>`
        <li class="gallery-item">
            <a href="${s.largeImageURL}" class="gallery-link">
                <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
            <div class="image-info">
                <p>👍 ${s.likes}</p>
                <p>👁️ ${s.views}</p>
                <p>💬 ${s.comments}</p>
                <p>⬇️ ${s.downloads}</p>
            </div>
          </a>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",i);const e=t.querySelector(".gallery-item").getBoundingClientRect().height;new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),window.scrollBy({top:e*2,behavior:"smooth"})}const p=document.querySelector(".search-form"),b=document.querySelector(".search-input"),u=document.querySelector(".wait-message"),E=document.querySelector(".gallery"),a=document.querySelector(".load-more-btn"),m=document.querySelector(".load-more-message");let g="",c=1,d=0;p.addEventListener("submit",async o=>{if(o.preventDefault(),g=b.value.trim(),!g){n.warning({title:"Error",message:"Input search string",position:"topRight"});return}c=1,E.innerHTML="",a.style.display="none",u.innerHTML='Loading images, please wait...<span class="loader"></span>';try{const t=await y(g,c);if(!t){n.error({title:"Error",message:"Something went wrong. Please try again",position:"topRight"});return}d=t.data.totalHits,t.data.hits.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(h(t.data.hits),t.data.hits.length<d&&(a.style.display="inline-block"))}catch(t){n.error({title:"Error",message:"Something went wrong. Please try again",position:"topRight"}),console.log(t)}finally{u.textContent=""}p.reset()});a.addEventListener("click",async()=>{c+=1,m.innerHTML='Loading more images, please wait...<span class="loader"></span>',a.disabled=!0;try{const o=await y(g,c);o.data.hits.length===0?(n.error({title:"Error",message:"Sorry, there are no more images to load.",position:"topRight"}),a.style.display="none"):(h(o.data.hits),c*40>=d&&(a.style.display="none",n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch(o){n.error({title:"Error",message:"Something went wrong. Please try again",position:"topRight"}),console.log(o)}finally{m.textContent="",a.disabled=!1}});
//# sourceMappingURL=index.js.map
