import{a as h,i as a,S as f}from"./assets/vendor-D3PmPE7A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const w="48876582-9b859673e779d9e5d61f29cd8",L="https://pixabay.com/api/";async function m(o,t=1,n=40){const i=new URLSearchParams({key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}),e=L+`?${i}`;try{return await h.get(e)}catch(r){return a.error({title:"Error",message:"Something went wrong. Try again!",position:"topRight"}),console.error("Error fetching images:",r),null}}function y(o){const t=document.querySelector(".gallery"),n=o.map(s=>`
        <li class="gallery-item">
            <a href="${s.largeImageURL}" class="gallery-link">
                <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
            <div class="image-info">
                <p>👍 ${s.likes}</p>
                <p>👁️ ${s.views}</p>
                <p>💬 ${s.comments}</p>
                <p>⬇️ ${s.downloads}</p>
            </div>
          </a>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",n);const e=t.querySelector(".gallery-item").getBoundingClientRect().height;new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),window.scrollBy({top:e*2,behavior:"smooth"})}const u=document.querySelector(".search-form"),S=document.querySelector(".search-input"),p=document.querySelector(".wait-message"),b=document.querySelector(".gallery"),l=document.querySelector(".load-more-btn");let g="",c=1,d=0;u.addEventListener("submit",async o=>{if(o.preventDefault(),g=S.value.trim(),!g){a.warning({title:"Error",message:"Input search string",position:"topRight"});return}c=1,b.innerHTML="",l.style.display="none",p.innerHTML='Loading images, please wait...<span class="loader"></span>';try{const t=await m(g,c);d=t.data.totalHits,t.data.hits.length===0?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(t.data.hits),t.data.hits.length<d&&(l.style.display="inline-block"))}catch(t){a.error({title:"Error",message:"Something went wrong. Please try again",position:"topRight"}),console.log(t)}finally{p.textContent=""}u.reset()});l.addEventListener("click",async()=>{c+=1,p.innerHTML='Loading more images, please wait...<span class="loader"></span>';try{const o=await m(g,c);o.data.hits.length===0?(a.error({title:"Error",message:"Sorry, there are no more images to load.",position:"topRight"}),l.style.display="none"):(y(o.data.hits),c*40>=d&&(l.style.display="none",a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch(o){a.error({title:"Error",message:"Something went wrong. Please try again",position:"topRight"}),console.log(o)}finally{p.textContent=""}});
//# sourceMappingURL=index.js.map
